### ISSUE TITLE
Custom Provider

### ISSUE THREAD

**Issue by erik-seifert** [portrino/shopware-hybrid-auth#16]
It would be nice to have a possibility too add an custom oauth provider. In our scenario we want to have drupal cms as an custom oauth provider.

**Comment by EvilBMP** [comment]
Did you take a look at https://github.com/portrino/shopware-hybrid-auth-typo3 ?

It is used to connect/ register users from an existing TYPO3 instance.

**Comment by erik-seifert** [comment]
Thanks. Got it. Try to add an Drupal OAuth Process with this module.

**Comment by EvilBMP** [comment]
Would be nice, if you share your results :-)
