### ISSUE TITLE
Fatal error: Uncaught Doctrine\ORM\Query\QueryException | Facebook login

### ISSUE THREAD

**Issue by dwalins** [portrino/shopware-hybrid-auth#5]
Hi,
Can't have the facebook login working. Everytime I try I get the error 

**Fatal error: Uncaught Doctrine\ORM\Query\QueryException: SELECT customers, attribute FROM Shopware\Models\Customer\Customer customers LEFT JOIN customers.attribute attribute WHERE attribute.facebookIdentity = ?1**

I've checked the table s_user_attribute in the database and the facebook_identity field is there but the model doesn't seem to be updated, am I missing something during the installation?

Thanks :)

**Comment by dwalins** [comment]
composer update 🤦‍♂️

**Comment by EvilBMP** [comment]
Normally, `composer install` should be enough 😎

**Comment by dwalins** [comment]
Thanks! Just posted it in case someone else would need it :)
