### ISSUE TITLE
 Uncaught Exception: User profile request failed! LinkedIn returned an invalid response

### ISSUE THREAD

**Issue by dwalins** [portrino/shopware-hybrid-auth#6]
Hi,
It's me again 😅
This time I'm trying to get working the LinkedIn part and seems to be some problem with the returned data but I can't figure out exactly what, any idea?

**Comment by EvilBMP** [comment]
Please try to put this in the "LinkedIn :: Fields" configuration field:

`id,email-address,first-name,last-name,headline,location,industry,picture-url,public-profile-url`

**Comment by dwalins** [comment]
Thank you very much, it is working indeed using that configuration. I founded an alternative solution and was deleting the $this->config["fields"] bits, but knowing this is much better ;)

**Comment by davitsargsyan** [comment]
It seems that this bug is reappearing again.
